name: opass-build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt -y autoremove
        sudo apt -y install build-essential cmake
    - name: Create build CMake
      run: |
        ./build.sh
    - name : Test Run 'opass' App
      run: |
        cd bin/
        ./opass -h
        ./opass -v
        ./opass
